name: Main CI Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate dummy package.json
        run: npm init -y

      - name: Add dummy scripts
        run: |
          jq '.scripts = {
            "lint": "echo Lint successful",
            "test": "echo Tests passed"
          }' package.json > tmp.json && mv tmp.json package.json

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test
