name: Python CI Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Create dummy app and test
        run: |
          echo "def add(a, b): return a + b" > app.py
          mkdir tests
          echo "from app import add\ndef test_add(): assert add(2, 3) == 5" > tests/test_app.py

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Run tests
        run: |
          pytest
