name: Predict Workflow Failure - RAG

on:
  workflow_dispatch:
    inputs:
      knowledge_path:
        description: 'Path to .txt knowledge base'
        required: true
        default: 'dynamic-knowledge/dynamic_combined_logs.txt'
      workflow_path:
        description: 'Path to GitHub workflow file'
        required: true
        default: '.github/workflows/main-ci.yml'
      prompt:
        description: 'RAG prompt'
        required: true
        default: 'Based on the knowledge, will the following workflow likely fail or pass? Just say FAIL or PASS with a brief reason.'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        sudo apt update
        curl -fsSL https://ollama.com/install.sh | sh
        pip install langchain langchain-community sentence-transformers faiss-cpu

    - name: Pull LLaMA2 model
      run: ollama pull llama2

    - name: Wait for Ollama
      run: sleep 10

    - name: Run RAG analysis
      run: |
        python3 dynamic_analyze.py \
          --workflow "${{ github.event.inputs.workflow_path }}" \
          --knowledge "${{ github.event.inputs.knowledge_path }}" \
          --query "${{ github.event.inputs.prompt }}" \
          --output prediction_output.txt

    - name: Upload prediction
      uses: actions/upload-artifact@v4
      with:
        name: rag-prediction-result
        path: prediction_output.txt
